#! /usr/bin/env bash
set -euo pipefail
# defined in bootstrap.sh
set -x
#Load lib.sh functions
. $(dirname "$(realpath "${BASH_SOURCE[0]}")")/lib.sh
update_channels () 
{ 
    local retVal;
    new_temp_worktree "$CHANNELS_BRANCH";
    pushd "$retVal";
    for i in */;
    do
        local branch="${i%-=-=-*}";
        local upstream_="${i##*-=-=-}";
        local upstream="${upstream_%*/}";
        git subtree pull --prefix "$i" "$upstream" "$branch";
    done;
    git_commit_all "updated channels";
    popd;
    close_temp_worktree "$retVal"
}
update_channels
